

# Site settings
title: Jakhnag
web-url: https://jhakhang.com
description: "Jakhang Podcast"
author: jhakhang
email: jakhang@gmail.com
lang: bo
copyright: "&#xA9; 2020"

#google tracking code
# gtag: 'G-HMK4JHPST9' --- Old
gtag: ' '

#RSS
googleplayownnder: jakhang@gmail.com
googleplayownauthor: jakhang
itunesname: jakhang
itunesemail: jakhang@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username: 


permalink: /:year/:title.html
paginate: 5
paginate_path: "blog/:num"

#Timezone
timezone: 
regenerate: true
incremental: true

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

plugins: 
  - jekyll-admin
  - jekyll-paginate


