

# Site settings
title: Jhakhang
web-url: https://jhakhang.com
description: "Jhakhang Podcast"
author: Jhakhang
thumbnail: "/assets/images/thumbnail-apple.png"
email: jhakhang@gmail.com
description: Jhakhang is a venue where a group of friends get together from time to time to discuss global issues and social phenomena that might interest Tibetan audiences. From art and culture to politics and society, we discuss a wide range of topics that have implications and consequences for the Tibetan world.
description-bo: "ཇ་ཁང་ནི་དུས་ནས་དུས་སུ་གྲོགས་པོ་ཚོ་ལྷན་འཛོམས་ཀྱིས། བོད་རིགས་མང་ཚོགས་ཀྱི་དོ་དབྱིངས་ཡོད་སའི་རྒྱལ་སྤྱིའི་གནད་དོན་དང་སྤྱི་ཚོགས་ཀྱི་འགྱུར་འགྲོས་སྐོར་ལ་གྲོས་བསྡུར་བྱེད་སའི་གླེང་སྟེགས་ཤིག་ཡིན། འདི་རུ་ང་ཚོས་བོད་པའི་སྤྱི་ཚོགས་ཁྱོན་ཡོངས་ལ་ཤུགས་རྐྱེན་དང་བག་ཆགས་གཏིང་ཟབ་འཇོག་གཞིའི་སྒྱུ་རྩལ་དང་རིག་གཞུང་། ཆབ་སྲིད་ནས་སྤྱི་ཚོགས་བར་གྱི་གཞི་རྒྱ་ཆེ་བའི་བརྗོད་དོན་སྣ་མང་ཐོག་གོ་བསྡུར་དང་ཁ་བརྡ་བྱེད་ཀྱི་ཡོད།"
lang: bo
copyright: "&#xA9; 2020"
spotify: "https://open.spotify.com/show/3sMzlhXuaXwYPLvc5dogaZ?si=guzg-DRlTR2NHm_inIV_9g&dl_branch=1"
soundcloud: "https://soundcloud.com/jhakhang"
amazon: "https://music.amazon.in/podcasts/6eb078a7-99d9-4b20-9a63-ed3086bc2adc/jhakhang"
google-podcast: "https://podcasts.google.com/feed/aHR0cHM6Ly9qaGFraGFuZy5jb20vcnNz"
#google tracking code
# gtag: 'G-HMK4JHPST9' --- Old
gtag: ' '
#RSS
googleplayownnder: jhakhang@gmail.com
googleplayownauthor: jhakhang
itunesname: jhakhang
itunesemail: jhakhang@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username: 


permalink: /:year/:title.html
paginate: 5
paginate_path: "blog/:num"

#Timezone
timezone: 
regenerate: true
incremental: true

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

plugins: 
  - jekyll-admin
  - jekyll-paginate


